/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bitmap;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;

public class Lab4 {
    public String getGreeting() {
        return "Starting Lab 4.";
    }

    public static void main(String[] args) {
        System.out.println(new Lab4().getGreeting());
        BufferedImage img = Lab4.readBMP("./src/main/resources/goldhill.bmp");
        System.out.println(img.getRGB(0,0)>>16&0xFF);
    }

    public static BufferedImage readBMP(String path) {
        File bmpFile = new File(path);
        BufferedImage img = null;
        try{
            img = ImageIO.read(bmpFile);
        }
        catch(IOException e) {
            System.err.println(e);
        }
        return img;
    }
}
