/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bitmap;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Lab4 classUnderTest = new Lab4();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
